steps:
  - name: gradle:6.8.2-jdk11
    entrypoint: gradle
    args: ["test"]
    id: Compile application and run tests

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        if test -f "/build/reports/tests/test/index.html"; then
            gsutil cp /build/reports/tests/test/index.html gs://pipeline_test_reports/testReport-$BUILD_ID.html
        fi

  - name: gradle:6.8.2-jdk11
    entrypoint: gradle
    args: [ "assemble" ]

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg=JAR_FILE=build/libs/*.jar'
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build Docker image

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push Docker image to Artifact registry

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _TRIGGER_ID: e40bbe54-57c7-4fef-ac54-4f4d9b3f0208
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: upskill-project
  _DEPLOY_REGION: us-central1
  _LABELS: gcb-trigger-id=e40bbe54-57c7-4fef-ac54-4f4d9b3f0208
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - upskill-project
